### ISSUE TITLE
README should mentions implementation limits: only works on public Go code from pkg.go.dev

### ISSUE THREAD

**Issue by dolmen** [chuongtrh/godepviz#2]
README should mention that [the implementation](https://github.com/chuongtrh/godepviz/blob/main/godep/godep.go#L123) uses `https://pkg.go.dev/...?tab=imports` to resolve imports and that it doesn't read local files, and so can't analyze private code.

**Comment by chuongtrh** [comment]
hi @dolmen 
Yes, it's really mentioned in Readme

**Comment by dolmen** [comment]
@chuongtrh Could you show me a screenshot? I had a second look at the README and I really don't see where it is mentionned that `godepviz` resolves explores dependencies only from online data.

**Comment by chuongtrh** [comment]
@dolmen You can find here
![image](https://github.com/chuongtrh/godepviz/assets/7924855/07a0ac89-149f-4b4f-9eab-39c25c40b263)
