### ISSUE TITLE
Use the GOPROXY protocol instead of pkg.go.dev

### ISSUE THREAD

**Issue by dolmen** [chuongtrh/godepviz#3]
To retrieve dependencies, use the [GOPROXY protocol](https://go.dev/ref/mod#goproxy-protocol) instead of querying `pkg.go.dev`.

**Comment by chuongtrh** [comment]
hi @dolmen 
Nice suggestion. Could you make PR for that?

**Comment by dolmen** [comment]
Well, my needs for a dependency graph involves modules hosted on private repositories which are not available via the Google Go proxy.

So, I'm sorry but, as this tool doesn't fit my needs, I don't intend to contribute this feature.

Instead I have plans (vaporware!) to work on a tool that would use data from the local Go module cache.
